# Generated by Django 3.2.15 on 2022-10-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackerraidapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='booked',
        ),
        migrations.AlterField(
            model_name='director',
            name='directcs',
            field=models.CharField(choices=[('Short Film', 'Short Film'), ('Film', 'Film'), ('TV Show', 'TV Show'), ('TV Commercial', 'TV Commercial')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('seat_no', 'seat_type', 'theater')},
        ),
    ]
