# Generated by Django 3.2.15 on 2023-03-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackerraidapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile',
            field=models.ImageField(upload_to='media/profiles'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='media/posters'),
        ),
    ]
