# Generated by Django 3.2.15 on 2023-01-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackerraidapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filmography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='rated',
            options={'verbose_name': 'Rated', 'verbose_name_plural': 'Rated'},
        ),
        migrations.RemoveField(
            model_name='director',
            name='directcs',
        ),
        migrations.AddField(
            model_name='director',
            name='directcs',
            field=models.ManyToManyField(to='blackerraidapp.Filmography'),
        ),
    ]
