# Generated by Django 3.2.15 on 2023-01-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackerraidapp', '0002_auto_20230108_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmography',
            options={'verbose_name': 'Filmography', 'verbose_name_plural': 'Filmography'},
        ),
        migrations.RenameField(
            model_name='rated',
            old_name='rated',
            new_name='name',
        ),
    ]
