# Generated by Django 3.2.15 on 2022-11-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blackerraidapp', '0002_auto_20221002_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showseat',
            name='seat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='show_seat_seat', to='blackerraidapp.seat'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('number_of_seats', 'time_stamp', 'booked', 'user', 'show')},
        ),
        migrations.AlterUniqueTogether(
            name='showseat',
            unique_together={('price', 'seat', 'intheater', 'booking')},
        ),
    ]
