# Generated by Django 3.2.15 on 2023-01-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackerraidapp', '0003_auto_20230109_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rated',
            new_name='Rating',
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='name',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rated',
        ),
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=models.ManyToManyField(to='blackerraidapp.Rating'),
        ),
    ]
